/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: junior.phillip (https://sketchfab.com/junior.phillip)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/eth-coin-e6bd61ef2fa54308ba0ef65507ead9c9
title: ETH Coin
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Ethcoin(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/ethcoin.gltf");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cone_2" position={[0, 0.5, 0]}>
                <mesh
                  name="Object_4"
                  geometry={nodes.Object_4.geometry}
                  material={materials["Material.001"]}
                  speed={1.5}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ethcoin.gltf");
